### ISSUE TITLE
[BUG] Local run fails with sh: react-scripts: command not found

### ISSUE THREAD

**Issue by karianna** [Markusgp/Untangle#107]
Followed instructions to run locally but it failed at the:

my-app@0.1.0 start
react-scripts start

with 

sh: react-scripts: command not found

**Comment by Karlo2001** [comment]
Hello @karianna,
Sorry for the delay, the team have been very busy with exams. This issue should now have been fixed, I am not able to make a new release at this point in time, so you would have to clone the project in order to get the changes.
Thanks for your support of the project
